package com.cloud.blog.dao;

import com.cloud.blog.dataObject.Articles;

public interface ArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int insert(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int insertSelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    Articles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int updateByPrimaryKeySelective(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Articles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articles
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    int updateByPrimaryKey(Articles record);
}