package com.cloud.blog.dao;

import com.cloud.blog.dataObject.LikedKey;

public interface LikedMapper {

    LikedKey selectByPrimaryKey(int id);
    LikedKey selectRelations(int userId, int contentId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    int deleteByPrimaryKey(LikedKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    int insert(LikedKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liked
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    int insertSelective(LikedKey record);
}