package com.cloud.blog.dataObject;

import java.util.Date;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.createDate
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.timestamp
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.content_type
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer contentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.mapping_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer mappingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.author_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer authorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.like
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer like;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.view
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private Integer view;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column content.comment
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.id
     *
     * @return the value of content.id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.id
     *
     * @param id the value for content.id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.createDate
     *
     * @return the value of content.createDate
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.createDate
     *
     * @param createdate the value for content.createDate
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.timestamp
     *
     * @return the value of content.timestamp
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.timestamp
     *
     * @param timestamp the value for content.timestamp
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setTimestamp(Integer timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.content_type
     *
     * @return the value of content.content_type
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.content_type
     *
     * @param contentType the value for content.content_type
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setContentType(Integer contentType) {
        this.contentType = contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.mapping_id
     *
     * @return the value of content.mapping_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getMappingId() {
        return mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.mapping_id
     *
     * @param mappingId the value for content.mapping_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setMappingId(Integer mappingId) {
        this.mappingId = mappingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.author_id
     *
     * @return the value of content.author_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.author_id
     *
     * @param authorId the value for content.author_id
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.like
     *
     * @return the value of content.like
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getLike() {
        return like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.like
     *
     * @param like the value for content.like
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.view
     *
     * @return the value of content.view
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public Integer getView() {
        return view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.view
     *
     * @param view the value for content.view
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setView(Integer view) {
        this.view = view;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column content.comment
     *
     * @return the value of content.comment
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column content.comment
     *
     * @param comment the value for content.comment
     *
     * @mbg.generated Sat Jan 12 21:33:54 EST 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}