package com.cloud.blog.dataObject;

public class LikedKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liked.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liked.userId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liked.contentId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private Integer contentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liked.id
     *
     * @return the value of liked.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liked.id
     *
     * @param id the value for liked.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liked.userId
     *
     * @return the value of liked.userId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liked.userId
     *
     * @param userid the value for liked.userId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liked.contentId
     *
     * @return the value of liked.contentId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public Integer getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liked.contentId
     *
     * @param contentid the value for liked.contentId
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setContentid(Integer contentid) {
        this.contentid = contentid;
    }
}