package com.cloud.blog.dataObject;

public class Pictures {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.discription
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private String discription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.src
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    private String src;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.id
     *
     * @return the value of pictures.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.id
     *
     * @param id the value for pictures.id
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.discription
     *
     * @return the value of pictures.discription
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.discription
     *
     * @param discription the value for pictures.discription
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.src
     *
     * @return the value of pictures.src
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.src
     *
     * @param src the value for pictures.src
     *
     * @mbg.generated Tue Feb 05 18:54:36 EST 2019
     */
    public void setSrc(String src) {
        this.src = src == null ? null : src.trim();
    }
}